[package]
name = "the_op_game_25"
version = "1.0.0"
edition = "2024"
description = "A version of the game Nim with a computer that cannot be beaten."
repository = "https://github.com/TheBestWebsite/DaRiggedRust"
readme = true
license = "MIT"
build = false
exclude = [".*", "/.*"]

[dependencies]
